### ISSUE TITLE
Could we differentiate between Pagirinya Satelite house and the #ROSHOP 

### ISSUE THREAD

**Issue by dutkulang** [WeAreYEF/pagirinya-satelite-house-prototype#1]
The ROSHOP is the building process documentation of the house, which is a going process while the Pagirinya Satelite how is the house it's self as it used by YEF for it's activities

**Comment by dutkulang** [comment]
this repo should hold little about the building process in which house came to be and more on the activities carried out at the space

**Comment by chardso** [comment]
It was the idea of the executive director

**Comment by dutkulang** [comment]
Ok

**Comment by timmwille** [comment]
Now we have it solved @vugawilliam @DutKulang @chardso  @PyGamma → check it out :)

**Comment by timmwille** [comment]
Maybe someone can take over the readme file and make it nicer/look suited to the PSH Use-Case specifically?

**Comment by chardso** [comment]
Who is maintaining this?

**Comment by dutkulang** [comment]
@vugawilliam can answer that
